pipeline {
agent any
  tools{
    maven 'maven'
  }
  stages{
stage("clean up"){
  steps{ 
  delete Dir()
  }
}
    stage("clone repo"){
  steps{ 
  sh" git clone https://github.com/Bayari123456/tp3.git"
  }
}
     stage("Generate backend image"){
  steps{ 
    dir ("backend"){
      sh "mvn clean install"
      sh "docker build -t backend  ."
     }
  }
     }
    stage("Run docker compose")
    steps{ 
    dir ("backend"){
      sh " docker compose up -d"
    
    
  }
    }
  }
}
  
}
